models:
    grab_lamp:
        repo_id: "1g0rrr/grab_lamp"
        control_time_s: 20
    insert_lamp:
        repo_id: "1g0rrr/insert_lamp"
        control_time_s: 22
    testing_lamp:
        repo_id: "1g0rrr/testing_lamp"
        control_time_s: 20
